apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: olm
  name: configmap-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["configmaps"]
  verbs: ["get", "watch", "list", "create", "delete"]
